$('.owl-carousel').owlCarousel({
    animateOut:'animate__slideOutUp',
    animateIn:'animate__slideInUp',
    loop:true,
    margin:10,
    nav:true,
    items:1,
    autoplay:true,
    autoplayTimeout:3000,
})